/**
 * Everything KIDDO can play, as data.
 *
 * Two kinds of sound and one rule about each. Music is long, loops, and is the
 * room the child is standing in; an effect is short, one-shot, and is a reply
 * to something they just did. Nothing else is allowed in here — a "sound" that
 * is neither is a sound that will eventually be playing over an instruction.
 *
 * Written as a registry rather than as string literals scattered through the
 * games for the same reason the game catalogue is: nothing that plays a sound
 * knows where the file lives or how loud it was mastered, so the day the real
 * KIDDO music is written it arrives here and nowhere else.
 *
 * ## Swapping the placeholders for the finished music
 *
 * Everything under `public/audio` is a placeholder, generated by
 * `scripts/make-placeholder-audio.mjs` — plain synthesised tones, written for
 * this repo, so there is nothing licensed here to get wrong. They exist so the
 * system is real and testable rather than theoretical.
 *
 * Replacing one is **one line below and nothing else**:
 *
 *     world: { src: "/audio/kiddo-world.wav", gain: 1, placeholder: true },
 *     world: { src: "/audio/kiddo-world.mp3", gain: 1 },
 *
 * Drop the file into `public/audio`, point `src` at it, and delete the
 * `placeholder` flag. The container does not have to match — `src` is fetched
 * and handed to `decodeAudioData`, so wav, mp3, ogg and m4a are all the same
 * to the engine — and no component, hook or test names a file or a format.
 * `gain` is the per-clip trim if the new master sits hotter than the old one;
 * nothing else needs touching.
 *
 * What a replacement has to be is written down once, in
 * `public/audio/README.md`, next to the files themselves.
 */

/** A one-shot reply to something the child did. */
export type SoundId = "tap" | "button" | "correct" | "retry" | "complete";

/** A looping bed. There is one for now, and the type is what keeps it honest. */
export type MusicId = "world";

export interface Clip {
  /** Path under `public/`. Any container the browser can decode. */
  src: string;
  /**
   * Per-clip trim, multiplied into its bus.
   *
   * Here so one sample that was mastered hot cannot force the whole bus down
   * and take every other sound with it. 1 means "as recorded".
   */
  gain?: number;
  /**
   * Still a synthesised stand-in, waiting for the real thing.
   *
   * Carried as data rather than as a comment so "what is left to record?" is
   * a question the registry answers. Delete the flag with the file it
   * describes; nothing reads it at runtime.
   */
  placeholder?: true;
}

/**
 * The looping beds.
 *
 * Gentle by construction, and then trimmed again here: a bed a child *notices*
 * is a bed that is competing with whatever KIDDO is asking them to do.
 */
export const MUSIC: Record<MusicId, Clip> = {
  world: { src: "/audio/kiddo-world.wav", gain: 1, placeholder: true },
};

/**
 * The replies.
 *
 * Short, soft and playful, and deliberately quieter than they could be. The
 * loudest thing in KIDDO should be a celebration, and only once per round.
 */
export const SOUNDS: Record<SoundId, Clip> = {
  /** A finger landing on something. The most-played sound in the product. */
  tap: { src: "/audio/tap.wav", gain: 0.7, placeholder: true },
  /** A control being used, rather than a game answer being given. */
  button: { src: "/audio/button.wav", gain: 0.7, placeholder: true },
  correct: { src: "/audio/correct.wav", gain: 0.9, placeholder: true },
  /**
   * "Let's try again" — warm and falling, never a buzzer.
   *
   * Named `retry` rather than anything harsher because that is the word the
   * whole product already uses for this moment: the pose KIDDO strikes, the
   * badge the tile wears, the `--color-retry` it wears it in. There is no
   * sound in KIDDO for having got something wrong, and the registry is where
   * that stops being possible to add by accident.
   */
  retry: { src: "/audio/retry.wav", gain: 0.75, placeholder: true },
  complete: { src: "/audio/complete.wav", gain: 1, placeholder: true },
};

export const MUSIC_IDS = Object.keys(MUSIC) as MusicId[];
export const SOUND_IDS = Object.keys(SOUNDS) as SoundId[];

/** The bed the home screen and the play experience stand in. */
export const WORLD_MUSIC: MusicId = "world";
